{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ required "values.yaml: namespace is required" .Values.namespace | quote }}
  name: {{ include "app.secretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: {{ default "Opaque" .Values.secret.type }}
{{- if .Values.secret.stringData }}
stringData:
  {{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- else if .Values.secret.data }}
data:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
